package com.openshift.portal.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Executable OpenShift CLI remediation command generated by FinAI")
public class FinAiCliSnippetDto {

    @Schema(description = "Command title or operation purpose", example = "Application du ResourceQuota recommandé")
    private String title;

    @Schema(description = "Exact copy-pasteable oc CLI command line", example = "oc patch resourcequota default -n spark-batch-analytics --type=merge -p '{\"spec\":{\"hard\":{\"requests.cpu\":\"6.8\"}}}'")
    private String command;

    @Schema(description = "Explanation of what this command will modify in OpenShift", example = "Redimensionne les requêtes CPU à 6.8 cœurs avec 20% de marge de sécurité sans impacter la production.")
    private String description;

    @Schema(description = "Target OpenShift namespace or cluster", example = "spark-batch-analytics")
    private String targetNamespace;
}
