package com.openshift.portal.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Interactive visualization chart generated by FinAI Copilot inside conversation")
public class FinAiChartDto {

    @Schema(description = "Unique chart identifier", example = "chart-top-waste")
    private String id;

    @Schema(description = "Chart visualization type: BAR, DONUT, or TREND", example = "BAR")
    private String type; // BAR, DONUT, TREND

    @Schema(description = "Main title of the chart", example = "Top 5 Namespaces les plus Gaspilleurs")
    private String title;

    @Schema(description = "Subtitle or context description", example = "Comparaison Quota Alloué vs Consommation Réelle")
    private String subtitle;

    @Schema(description = "Central summary metric or total value", example = "$11,240 / mois")
    private String totalValue;

    @Schema(description = "Unit of measurement", example = "$/mois")
    private String unit;

    @Builder.Default
    @Schema(description = "List of chart data points")
    private List<FinAiChartDataPointDto> points = new ArrayList<>();
}
