package com.openshift.portal.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Synthesized FinAI Copilot response containing diagnosis, metrics, CLI remediation snippets, and strategic roadmap")
public class FinAiResponseDto {

    @Schema(description = "Original query submitted by operator")
    private String query;

    @Schema(description = "Executive headline summary", example = "Diagnostic d'optimisation : $21,692.86 de gaspillage mensuel identifié")
    private String headline;

    @Schema(description = "In-depth markdown analysis and strategic justification")
    private String analysisMarkdown;

    @Builder.Default
    @Schema(description = "Key metrics summary")
    private List<FinAiMetricItemDto> metrics = new ArrayList<>();

    @Builder.Default
    @Schema(description = "List of executable OpenShift oc CLI remediation commands")
    private List<FinAiCliSnippetDto> cliCommands = new ArrayList<>();

    @Builder.Default
    @Schema(description = "Suggested follow-up operator questions")
    private List<String> suggestedFollowUps = new ArrayList<>();

    @Builder.Default
    @Schema(description = "Prioritized strategic execution steps")
    private List<String> executionPlan = new ArrayList<>();

    @Builder.Default
    @Schema(description = "Interactive visualization charts generated by FinAI Copilot")
    private List<FinAiChartDto> charts = new ArrayList<>();

    @Schema(description = "Confidence score (0.0 to 1.0)", example = "0.96")
    private Double confidenceScore;

    @Schema(description = "Timestamp of generation")
    private Instant timestamp;
}
